services:
  cart-service:
    image: public.ecr.aws/j1n2c2p2/microservices-demo/cartservice:v0.3.9
    env_file:
      - 'variables.env'
    environment:
      - PORT=7070
    volumes:
      - ./src/cartservice:/src
  checkout-service:
    image: public.ecr.aws/j1n2c2p2/microservices-demo/checkoutservice:v0.4.0
    env_file:
      - 'variables.env'
    environment:
      - PORT=5050
  product-catalog-service:
    image: public.ecr.aws/j1n2c2p2/microservices-demo/productcatalogservice:v0.3.9
    env_file:
      - 'variables.env'
    environment:
      - PORT=3550
  skyramp:
    image: public.ecr.aws/j1n2c2p2/rampup/worker:latest
    volumes:
      - skyramp:/etc/skyramp
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 35142:35142
    env_file:
      - 'variables.env'
    restart: always

volumes:
  skyramp:
