version: '3.8'

services:
  adservice:
    build:
      context: ./adservice/
      dockerfile: Dockerfile
    image: iscanprint/adservice:2.0
    env_file:
      - 'variables.env'
    environment:
      - PORT=9550

  cartservice:
    build:
      context: ./cartservice/
      dockerfile: Dockerfile
    image: iscanprint/cartservice:2.0
    env_file:
      - 'variables.env'
    environment:
      - PORT=7070

  checkoutservice:
    build:
      context: ./checkoutservice/
      dockerfile: Dockerfile
    image: iscanprint/checkoutservice:2.0
    env_file:
      - 'variables.env'
    environment:
      - PORT=5050

  currencyservice:
    build:
      context: ./currencyservice/
      dockerfile: Dockerfile
    image: iscanprint/currencyservice:2.0
    env_file:
      - 'variables.env'
    environment:
      - PORT=7000
    ports:
      - 50000:50000
      - 60000:60000

  emailservice:
    build:
      context: ./emailservice/
      dockerfile: Dockerfile
    image: iscanprint/emailservice:2.0
    env_file:
      - 'variables.env'
    environment:
      - PORT=5000

  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    image: iscanprint/frontend:2.0
    ports:
      - 8080:80
    env_file:
      - 'variables.env'
    environment:
      - PORT=80

  paymentservice:
    build:
      context: ./paymentservice/
      dockerfile: Dockerfile
    image: iscanprint/paymentservice:2.0
    env_file:
      - 'variables.env'
    environment:
      - PORT=50051

  productcatalogservice:
    build:
      context: ./productcatalogservice/
      dockerfile: Dockerfile
    image: iscanprint/productcatalogservice:2.0
    env_file:
      - 'variables.env'
    environment:
      - PORT=3550

  recommendationservice:
    build:
      context: ./recommendationservice/
      dockerfile: Dockerfile
    image: iscanprint/recommendationservice:2.0
    env_file:
      - 'variables.env'
    environment:
      - PORT=8080

  shippingservice:
    build:
      context: ./shippingservice/
      dockerfile: Dockerfile
    image: iscanprint/shippingservice:2.0
    env_file:
      - 'variables.env'
    environment:
      - PORT=50051

  clients:
    build:
      context: ./clients/
      dockerfile: Dockerfile
    image: public.ecr.aws/j1n2c2p2/microservices-demo/clients:v0.0.2
