apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: sample-microservices
build:
  artifacts:
    - image: cartservice
      context: src/cartservice
      docker:
        dockerfile: Dockerfile
    - image: checkoutservice
      context: src/checkoutservice
      docker:
        dockerfile: Dockerfile
    - image: productcatalogservice
      context: src/productcatalogservice
      docker:
        dockerfile: Dockerfile 
deploy:
  helm:
    releases:
      - name: sample-microservices
        chartPath: skyramp/demo/sample-microservices
        valuesFiles:
          - skyramp/demo/sample-microservices/values.yaml
        version: 0.1.0
