{{- if .Values.cartService.create }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.cartService.name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      name: {{ .Values.cartService.name }}
  template:
    metadata:
      labels:
        name: {{ .Values.cartService.name }}
    spec:
      containers:
      - name: {{ .Values.cartService.name }}
        image: pellepedro/codespace-godev:latest
        workingDir: /src
        securityContext:
          capabilities:
            add:
              - SYS_PTRACE
        ports:
        - containerPort:  {{ .Values.cartService.containerPort }}
        env:
          - name: REDIS_ADDR
            value: "{{ .Values.cartDatabase.name }}:{{ .Values.cartDatabase.containerPort }}"
          - name: DISABLE_PROFILER
            value: "1"
          - name: DISABLE_DEBUGGER
            value: "1"
          - name: DISABLE_STATS
            value: "1"
          - name: DISABLE_TRACING
            value: "1"
        command:
          - "/bin/bash"
          - "-c"
          - |
            go mod download
            reload-debugger &
            sleep 360000
        volumeMounts:
          - name: cart-service-mount
            mountPath: /src
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "0.5"
            memory: "256Mi"
      volumes:
        - name: cart-service-mount
          hostPath:
            path: /cartservice
---
apiVersion: v1
kind: Service
metadata:
  annotations:
     skyramp.dev/protocol: {{ .Values.cartService.protocol}}
  name: {{ .Values.cartService.name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
  - port:  {{ .Values.cartService.servicePort}}
    name:  {{ .Values.cartService.name }}
  selector:
    name: {{ .Values.cartService.name }}
{{- end }}
