---
apiVersion: v1
kind: Service
metadata:
  name: cart-service
  namespace: codespace
spec:
  selector:
    app.kubernetes.io/name: cart-service
  ports:
    - protocol: TCP
      port: 60000
      targetPort: 60000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: cart-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cart-service
    spec:
      containers:
        - name: devcontainer
          securityContext:
            capabilities:
              add:
              - SYS_PTRACE
          image: codespace-godev:latest
          workingDir: /src
          env:
          - name: DISABLE_PROFILER
            value: "1"
          - name: DISABLE_DEBUGGER
            value: "1"
          - name: DISABLE_STATS
            value: "1"
          - name: DISABLE_TRACING
            value: "1"
          #command: ["sleep","3600"]
          command:
            - "/bin/bash"
            - "-c"
            - |
              go mod download
              sleep 3600
          volumeMounts:
            - name: cart-service-mount
              mountPath: /src
          imagePullPolicy: Never
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
            requests:
              cpu: "0.5"
              memory: "256Mi"
      volumes:
        - name: cart-service-mount
          hostPath:
            path: /cartservice

