containers:
  - name: product-catalog-service
    image:
      repository: public.ecr.aws/j1n2c2p2/microservices-demo/productcatalogservice
      tag: v0.3.9
    services:
      - product-catalog-service-port60000
    envs:
      PORT: "3550"
      DISABLE_STATS: "1"
      DISABLE_PROFILER: "1"
      DISABLE_TRACING: "1"

services:
  - name: product-catalog-service-port60000
    port: 60000
    protocol: rest
    endpoints:
      - get-product
      - get-products
      - search-products

endpoints:
  - name: get-product
    path: "/get-product"
    methods:
      - type: 'GET'
        responseValue: GetProductResponse
        name: get-product-get

  - name: get-products
    path: "/get-products"
    methods:
      - type: 'GET'
        responseValue: GetProductsResponse
        name: get-products-get

  - name: search-products
    path: "/search-products"
    methods:
      - type: 'GET'
        responseValue: SearchProductsResponse
        name: search-products-get

responseValues:
  - name: GetProductResponse
    blob: |
      {
        "id": "OLJCESPC7Z",
        "name": "Sunglasses",
        "description": "Add a modern touch to your outfits with these sleek aviator sunglasses.",
        "picture": "/static/img/products/sunglasses.jpg",
        "price_usd": {
          "currency_code": "USD",
          "units": 19,
          "nanos": 99000000
        },
        "categories": [
          "accessories",
          "fashion"
        ]
      }
  - name: GetProductsResponse
    blob: |
      [
        {
          "id": "OLJCESPC7Z",
          "name": "Sunglasses",
          "description": "Add a modern touch to your outfits with these sleek aviator sunglasses.",
          "picture": "/static/img/products/sunglasses.jpg",
          "price_usd": {
            "currency_code": "USD",
            "units": 19,
            "nanos": 99000000
          },
          "categories": [
            "accessories",
            "fashion"
          ]
        },
        {
          "id": "OLJCESPC7Z",
          "name": "Sunglasses",
          "description": "Add a modern touch to your outfits with these sleek aviator sunglasses.",
          "picture": "/static/img/products/sunglasses.jpg",
          "price_usd": {
            "currency_code": "USD",
            "units": 19,
            "nanos": 99000000
          },
          "categories": [
            "accessories",
            "fashion"
          ]
        }
      ]

  - name: SearchProductsResponse
    blob: |
      [
          {
             "id": "LS4PSXUNUM",
             "name": "Salt & Pepper Shakers",
             "description": "Add some flavor to your kitchen.",
             "picture": "/static/img/products/salt-and-pepper-shakers.jpg",
             "priceUsd": {
               "currencyCode": "USD",
               "units": 18,
               "nanos": 490000000
             },
             "categories": [
               "kitchen"
             ]
           },
           {
             "id": "9SIQT8TOJO",
             "name": "Bamboo Glass Jar",
             "description": "This bamboo glass jar can hold 57 oz (1.7 l) and is perfect for any kitchen.",
             "picture": "/static/img/products/bamboo-glass-jar.jpg",
             "priceUsd": {
               "currencyCode": "USD",
               "units": 5,
               "nanos": 490000000
             },
             "categories": [
               "kitchen"
             ]
          }
      ]
