services:
  cartservice:
    build:
      context: ./cartservice/.
      dockerfile: Dockerfile
    image: public.ecr.aws/j1n2c2p2/microservices-demo/cartservice:latest
    env_file:
      - 'variables.env'
    environment:
      - PORT=7070
      - REST_PORT=60000
    ports:
      - 60003:60000
    networks:
      - devcontainer_default 
  checkoutservice:
    build:
      context: ./checkoutservice/.
      dockerfile: Dockerfile
    image: public.ecr.aws/j1n2c2p2/microservices-demo/checkoutservice:v0.4.1
    env_file:
      - 'variables.env'
    environment:
      - PORT=5050
      - REST_PORT=60000
    ports:
      - 60001:60000
    networks:
      - devcontainer_default
  # paymentservice:
  #   build:
  #     context: ./paymentservice/.
  #     dockerfile: Dockerfile
  #   image: public.ecr.aws/j1n2c2p2/microservices-demo/paymentservice:latest
  #   env_file:
  #     - 'variables.env'
  #   environment:
  #     - PORT=50051
  #     - REST_PORT=60000
  #   ports:
  #     - 50051:60000
  productcatalogservice:
    build:
      context: ./productcatalogservice/.
      dockerfile: Dockerfile
    image: public.ecr.aws/j1n2c2p2/microservices-demo/productcatalogservice:latest
    env_file:
      - 'variables.env'
    environment:
      - PORT=3550
      - REST_PORT=60000
    ports:
      - 60002:60000
    networks:
      - devcontainer_default
    
networks:
  devcontainer_default:
    external: true